name: Cleanups
on:
  workflow_dispatch:
  schedule:
    - cron: "20 3 * * 5"
jobs:
  ghcr-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: cleanup old images (>30 days)
      uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        exclude-tags: latest
        keep-n-tagged: 5
        older-than: 30days
