name: Image build

on:
  push:
    paths:
      - Dockerfile

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
      
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # https://github.com/docker/setup-qemu-action
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v3  # https://github.com/docker/setup-buildx-action
      - 
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.5.0
      - 
        name: Read versions
        id: versions
        run: |
          awk -f versions.awk Dockerfile >> $GITHUB_OUTPUT
      - 
        name: Login to registry ${{ env.REGISTRY }}
        if: ${{ github.ref_name == 'main' }}
        uses: docker/login-action@v3  # https://github.com/docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract Docker metadata
        id: metadata
        if: ${{ github.ref_name == 'main' }}
        uses: docker/metadata-action@v5  # https://github.com/docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - 
        name: Build app
        uses: docker/build-push-action@v6  # https://github.com/docker/build-push-action
        with:
          push: ${{ github.ref_name == 'main' }}
          context: .
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.versions.outputs.TARGET_VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.versions.outputs.TARGET_VERSION }}-${{ steps.versions.outputs.SYSTEMD_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
